/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nvelizl
 */
public class ListadoProv extends javax.swing.JFrame {
    private NomCrearNomina ventanaSecundaria;
    PreparedStatement ps;
    ResultSet rs;
    DefaultTableModel modeloTableProv = new DefaultTableModel() {
    private NomCrearNomina ventanaSecundaria;        
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }  
            
            
            
        };
    private String datos;
    //NomCrearNomina aggProv = new NomCrearNomina();
    
    public ListadoProv() {
        
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblListProv3 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblDatosFiltro = new java.awt.Label();
        button1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblListProv3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tblListProv3);

        jLabel7.setText("RUT:");

        button1.setLabel("button1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDatosFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatosFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarTabla();
    }//GEN-LAST:event_formWindowOpened

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
          
            //controlar que la table no este vacia
            if (tblListProv3.getRowCount()> 0) {
                int filaSeleccionada = tblListProv3.getSelectedRow();
                //Sa valida que se haya seleccionado un registro
                if (filaSeleccionada !=-1 ) {
                    
                    //int numColumnas = tblListProv3.getColumnCount();//obtengo la id del proveedor que deseo modificar
                    //String[] datosFilat = new String[4];
                    //Obtener Datos de la fila seleccionanda;
                    //Object[] datosFilaS = new Object[6];
                    
                    String datosFilat1 = (String) tblListProv3.getValueAt(filaSeleccionada, 1);
                    String datosFilat2 = (String) tblListProv3.getValueAt(filaSeleccionada, 2);
                    String datosFilat3 = (String) tblListProv3.getValueAt(filaSeleccionada, 3);
                    String datosFilat4 = (String) tblListProv3.getValueAt(filaSeleccionada, 4);
                    String datosFilat5 = (String) tblListProv3.getValueAt(filaSeleccionada, 5);
                    //Traerdatos datosFilat = new Traerdatos(datosFilat2, datosFilat3, datosFilat4, datosFilat5);
                    Traerdatos traerdatos = new Traerdatos(datosFilat1, datosFilat2, datosFilat3, datosFilat4, datosFilat5);
                            ventanaSecundaria.traeDatos(traerdatos);
        //int idPro = Integer.parseInt(String.valueOf(tblListProv3.getValueAt(tblListProv3.getSelectedRow(), 0)));
                    
        
        // Verificar si la ventana está abierta
        //while (ventanaSecundaria != null && ventanaSecundaria.isVisible()) {
            // Llamar al método público en VentanaSecundaria para actualizar el JTextField
            
           // ventanaSecundaria.traeDatos(traerdatos);
             //        this.dispose();
                     //   if (ventanaSecundaria.isVisible()) {
                    
                    if (ventanaSecundaria  != null){
                       
                       ventanaSecundaria.toFront();
                       this.dispose();
                    }
                
            }}
    }//GEN-LAST:event_button1ActionPerformed
    
    
    // Resto del código

    // Método para establecer la instancia de NomCrearNomina
    public void setVentanaSecundaria(NomCrearNomina ventanaSecundaria) {
        this.ventanaSecundaria = ventanaSecundaria;
    }

    
   
    
    
        
        
    public void setDatos(String datos){
        this.datos = datos;
        lblDatosFiltro.setText(datos);
    }
    
    public void cargarTabla(){
        
        
        String titulosProv[] = {"ID", "RUT", "NOMBRE", "NRO. DE CUENTA", "COD. BANCO", "EMAIL", "SUCURSAL" };
        modeloTableProv.setColumnIdentifiers(titulosProv);//modeloTableProv
        
        //String sql = "Select * from proveedor";
        
        String [] registros = new String[7];
        
        java.sql.Connection cnx = null;
        try
            {
                cnx = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/portalPagosKovacs?serverTimezone=UTC", "root", "admin1234");}
        catch (java.sql.SQLException ex)
        {
        System.out.println("SQLException: " + ex.getMessage());System.out.println("SQLState: " + ex.getSQLState());
        System.out.println("VendorError: " + ex.getErrorCode());
        }
        
        
        
        //traer los proveedores de la base de datos
        //List <Proveedor> listaProveedores = control.traerProveedores();
        
        try {
           
            ps = cnx.prepareStatement("Select * from proveedor where RUTPROV = ?");
            ps.setString(1, lblDatosFiltro.getText());
            rs= ps.executeQuery();
            
            while (rs.next()) {
                registros[0]=rs.getString("IDPROV");
                registros[1]=rs.getString("RUTPROV");
                registros[2]=rs.getString("NOMBREPROV");
                registros[3]=rs.getString("CODIGOCTAPROV");
                registros[4]=rs.getString("NUMEROCTAPROV");
                registros[5]=rs.getString("EMAILPROV");
                registros[6]=rs.getString("SUCURSALPROV");
                modeloTableProv.addRow(registros);
                
                
                /*txtNombreProvNomina.setText(String.valueOf(rs.getString("NOMBREPROV")));
                txtEmailProvNomina.setText(String.valueOf(rs.getString("EMAILPROV")));
                txtNumeroCuentaProvNom.setText(String.valueOf(rs.getInt("NUMEROCTAPROV")));
                txtCodigoCuentaProvNom.setText(String.valueOf(rs.getInt("CODIGOCTAPROV")));*/
            } tblListProv3.setModel(modeloTableProv);
             
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No se encuentra el proveedor");
        }
        
        
        };
        public void enviarDatosMouseClicked(java.awt.event.MouseEvent evt){
            
        }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private java.awt.Label lblDatosFiltro;
    private javax.swing.JTable tblListProv3;
    // End of variables declaration//GEN-END:variables


}
