/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;



import ExportarExcell.ExportarJtabletoExcell;
import java.io.IOException;


import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author nvelizl
 */
public class NomCrearNomina extends javax.swing.JFrame {

    
    PreparedStatement ps;
    ResultSet rs;
     DefaultTableModel modeloTableNomina = new DefaultTableModel() {
            
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }  
            
            
            
        };
      
    public NomCrearNomina() {
        initComponents();   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRutNomina = new javax.swing.JTextField();
        txtNombreProvNomina = new javax.swing.JTextField();
        txtOpNomina = new javax.swing.JTextField();
        txtNumeroCuentaProvNom = new javax.swing.JTextField();
        txtCodigoCuentaProvNom = new javax.swing.JTextField();
        txtEmailProvNomina = new javax.swing.JTextField();
        txtGlosaNomina = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        txtMontoDoc11Nomina = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtDoc11Nomina = new javax.swing.JTextField();
        txtDoc10Nomina = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtMontoDoc10Nomina = new javax.swing.JTextField();
        txtMontoDoc9Nomina = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtDoc9Nomina = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtDoc8Nomina = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtMontoDoc8Nomina = new javax.swing.JTextField();
        txtMontoDoc7Nomina = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtDoc7Nomina = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtDoc6Nomina = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txtMontoDoc6Nomina = new javax.swing.JTextField();
        txtMontoDoc5Nomina = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtDoc5Nomina = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtDoc4Nomina = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txtMontoDoc4Nomina = new javax.swing.JTextField();
        txtMontoDoc3Nomina = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txtDoc3Nomina = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txtDoc2Nomina = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txtMontoDoc2Nomina = new javax.swing.JTextField();
        txtMontoDoc1Nomina = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        txtDoc1Nomina = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnAgregarFila = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDatosNomina = new javax.swing.JTable();
        btnExportarAExcell = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanelPropertyChange(evt);
            }
        });

        jLabel1.setText("NOMBRE");

        jLabel2.setText("RUT");

        jLabel3.setText("CODIGO  CTA.");

        jLabel4.setText("OP");

        jLabel5.setText("NUMERO DE CUENTA");

        jLabel6.setText("CORREO");

        jLabel7.setText("GLOSA");

        jLabel8.setText("DOCUMENTOS:");

        jLabel30.setText("DOC. 11");

        txtMontoDoc11Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoDoc11NominaActionPerformed(evt);
            }
        });

        jLabel31.setText("VALOR 11");

        txtDoc11Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoc11NominaActionPerformed(evt);
            }
        });

        txtDoc10Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoc10NominaActionPerformed(evt);
            }
        });

        jLabel32.setText("DOC. 10");

        jLabel33.setText("VALOR 10");

        txtMontoDoc10Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoDoc10NominaActionPerformed(evt);
            }
        });

        txtMontoDoc9Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoDoc9NominaActionPerformed(evt);
            }
        });

        jLabel34.setText("VALOR 9");

        txtDoc9Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoc9NominaActionPerformed(evt);
            }
        });

        jLabel35.setText("DOC. 9");

        jLabel36.setText("DOC. 8");

        txtDoc8Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoc8NominaActionPerformed(evt);
            }
        });

        jLabel37.setText("VALOR 8");

        txtMontoDoc8Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoDoc8NominaActionPerformed(evt);
            }
        });

        txtMontoDoc7Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoDoc7NominaActionPerformed(evt);
            }
        });

        jLabel38.setText("VALOR 7");

        txtDoc7Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoc7NominaActionPerformed(evt);
            }
        });

        jLabel39.setText("DOC. 7");

        jLabel40.setText("DOC. 6");

        txtDoc6Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoc6NominaActionPerformed(evt);
            }
        });

        jLabel41.setText("VALOR 6");

        txtMontoDoc6Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoDoc6NominaActionPerformed(evt);
            }
        });

        txtMontoDoc5Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoDoc5NominaActionPerformed(evt);
            }
        });

        jLabel42.setText("VALOR 5");

        txtDoc5Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoc5NominaActionPerformed(evt);
            }
        });

        jLabel43.setText("DOC. 5");

        jLabel44.setText("DOC. 4");

        txtDoc4Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoc4NominaActionPerformed(evt);
            }
        });

        jLabel45.setText("VALOR 4");

        txtMontoDoc4Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoDoc4NominaActionPerformed(evt);
            }
        });

        txtMontoDoc3Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoDoc3NominaActionPerformed(evt);
            }
        });

        jLabel46.setText("VALOR 3");

        txtDoc3Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoc3NominaActionPerformed(evt);
            }
        });

        jLabel47.setText("DOC. 3");

        jLabel48.setText("DOC. 2");

        txtDoc2Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoc2NominaActionPerformed(evt);
            }
        });

        jLabel49.setText("VALOR 2");

        txtMontoDoc2Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoDoc2NominaActionPerformed(evt);
            }
        });

        txtMontoDoc1Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoDoc1NominaActionPerformed(evt);
            }
        });

        jLabel50.setText("VALOR 1");

        txtDoc1Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoc1NominaActionPerformed(evt);
            }
        });

        jLabel51.setText("DOC. 1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtMontoDoc1Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtMontoDoc2Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtMontoDoc3Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtMontoDoc4Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtMontoDoc5Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtMontoDoc6Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtMontoDoc7Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtMontoDoc8Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtMontoDoc9Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtMontoDoc10Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtMontoDoc11Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtDoc1Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtDoc2Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtDoc3Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtDoc4Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtDoc5Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtDoc6Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtDoc7Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtDoc8Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtDoc9Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtDoc10Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtDoc11Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(129, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(jLabel47)
                    .addComponent(jLabel51)
                    .addComponent(jLabel44)
                    .addComponent(jLabel43)
                    .addComponent(jLabel40)
                    .addComponent(jLabel36)
                    .addComponent(jLabel39)
                    .addComponent(jLabel35)
                    .addComponent(jLabel32)
                    .addComponent(jLabel30))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(jLabel46)
                    .addComponent(jLabel45)
                    .addComponent(jLabel42)
                    .addComponent(jLabel41)
                    .addComponent(jLabel38)
                    .addComponent(jLabel37)
                    .addComponent(jLabel34)
                    .addComponent(jLabel33)
                    .addComponent(jLabel31))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDoc1Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDoc2Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDoc3Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDoc4Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDoc5Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDoc6Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDoc7Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDoc8Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDoc9Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDoc10Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDoc11Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(9, 9, 9)
                    .addComponent(jLabel50)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMontoDoc1Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMontoDoc2Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMontoDoc3Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMontoDoc4Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMontoDoc5Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMontoDoc6Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMontoDoc7Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMontoDoc8Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMontoDoc9Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMontoDoc10Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMontoDoc11Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(27, Short.MAX_VALUE)))
        );

        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnAgregarFila.setText("AGREGAR FILA");
        btnAgregarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFilaActionPerformed(evt);
            }
        });

        tblDatosNomina.setBackground(new java.awt.Color(255, 255, 255));
        tblDatosNomina.setForeground(new java.awt.Color(0, 0, 0));
        tblDatosNomina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDatosNomina.setAutoResizeMode(0);
        tblDatosNomina.setSelectionBackground(new java.awt.Color(255, 51, 51));
        tblDatosNomina.setShowGrid(true);
        tblDatosNomina.getTableHeader().setReorderingAllowed(false);
        tblDatosNomina.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblDatosNominaPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(tblDatosNomina);

        btnExportarAExcell.setText("EXPORTAR A EXCELL");
        btnExportarAExcell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarAExcellActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOpNomina, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNumeroCuentaProvNom, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreProvNomina, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addComponent(txtRutNomina, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoCuentaProvNom, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGlosaNomina)
                            .addComponent(txtEmailProvNomina)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(btnAgregarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExportarAExcell, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(txtCodigoCuentaProvNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmailProvNomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGlosaNomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(txtRutNomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(txtNombreProvNomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOpNomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNumeroCuentaProvNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarFila)
                    .addComponent(btnExportarAExcell))
                .addGap(265, 265, 265))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanelPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelPropertyChange

    private void txtDoc1NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoc1NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoc1NominaActionPerformed

    private void txtMontoDoc1NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoDoc1NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoDoc1NominaActionPerformed

    private void txtMontoDoc2NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoDoc2NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoDoc2NominaActionPerformed

    private void txtDoc2NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoc2NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoc2NominaActionPerformed

    private void txtDoc3NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoc3NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoc3NominaActionPerformed

    private void txtMontoDoc3NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoDoc3NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoDoc3NominaActionPerformed

    private void txtMontoDoc4NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoDoc4NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoDoc4NominaActionPerformed

    private void txtDoc4NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoc4NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoc4NominaActionPerformed

    private void txtDoc5NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoc5NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoc5NominaActionPerformed

    private void txtMontoDoc5NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoDoc5NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoDoc5NominaActionPerformed

    private void txtMontoDoc6NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoDoc6NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoDoc6NominaActionPerformed

    private void txtDoc6NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoc6NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoc6NominaActionPerformed

    private void txtDoc7NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoc7NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoc7NominaActionPerformed

    private void txtMontoDoc7NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoDoc7NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoDoc7NominaActionPerformed

    private void txtMontoDoc8NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoDoc8NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoDoc8NominaActionPerformed

    private void txtDoc8NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoc8NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoc8NominaActionPerformed

    private void txtDoc9NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoc9NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoc9NominaActionPerformed

    private void txtMontoDoc9NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoDoc9NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoDoc9NominaActionPerformed

    private void txtMontoDoc10NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoDoc10NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoDoc10NominaActionPerformed

    private void txtDoc10NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoc10NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoc10NominaActionPerformed

    private void txtDoc11NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoc11NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoc11NominaActionPerformed

    private void txtMontoDoc11NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoDoc11NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoDoc11NominaActionPerformed

    private void btnAgregarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFilaActionPerformed
    String rutProvNom = txtRutNomina.getText(); 
    String nombreProvNom = txtNombreProvNomina.getText();
    int modalidadProvNom = Integer.parseInt(txtOpNomina.getText());
    int nroCtaProvNom = Integer.parseInt(txtNumeroCuentaProvNom.getText());
    int codCtaProvNom =  Integer.parseInt(txtCodigoCuentaProvNom.getText());
    String numeroDoc1Nom = txtDoc1Nomina.getText();
    int montoDoc1Nom  =  Integer.parseInt(txtMontoDoc1Nomina.getText());
    String numeroDoc2Nom  =  txtDoc2Nomina.getText();
    int montoDoc2Nom =   Integer.parseInt(txtMontoDoc2Nomina.getText());
    String numeroDoc3Nom =   txtDoc3Nomina.getText();
    int montoDoc3Nom =  Integer.parseInt(txtMontoDoc3Nomina.getText());
    String numeroDoc4Nom =  txtDoc4Nomina.getText();
    int montoDoc4Nom  = Integer.parseInt(txtMontoDoc4Nomina.getText());
    String numeroDoc5Nom  = txtDoc5Nomina.getText();
    int montoDoc5Nom =  Integer.parseInt(txtMontoDoc5Nomina.getText());
    String numeroDoc6Nom  =  txtDoc6Nomina.getText();
    int montoDoc6Nom = Integer.parseInt(txtMontoDoc6Nomina.getText());
    String numeroDoc7Nom =  txtDoc7Nomina.getText();
    int montoDoc7Nom = Integer.parseInt(txtMontoDoc7Nomina.getText());
    String numeroDoc8Nom =  txtDoc8Nomina.getText();
    int montoDoc8Nom  = Integer.parseInt(txtMontoDoc8Nomina.getText());
    String numeroDoc9Nom =  txtDoc9Nomina.getText();
    int montoDoc9Nom  = Integer.parseInt(txtMontoDoc9Nomina.getText());
    String numeroDoc10Nom  =  txtDoc10Nomina.getText();
    int montoDoc10Nom =  Integer.parseInt(txtMontoDoc10Nomina.getText());
    String numeroDoc11Nom  =  txtDoc11Nomina.getText();
    int montoDoc11Nom = Integer.parseInt(txtMontoDoc11Nomina.getText());
    
    String emailProvNom  =  txtEmailProvNomina.getText();
    String glosaNom  =  txtGlosaNomina.getText();
    
    //Aqui creo una fila con la cantidad de columnas que necesito para mi tabla, y 
    //le asigno una caja de texto a cada columna, de acuerdo a los datos que necesita.
    
    //Se crea una matriz de tipo object para que registro distintos tipos de datos.
    Object []  datosFila =new Object[30];
    
    datosFila[0] = rutProvNom;
    datosFila[1] = nombreProvNom;
    datosFila[2] = modalidadProvNom;
    datosFila[3] = nroCtaProvNom;
    datosFila[4] = codCtaProvNom;
    datosFila[5] = numeroDoc1Nom;
    datosFila[6] = montoDoc1Nom;
    datosFila[7] = numeroDoc2Nom;
    datosFila[8] = montoDoc2Nom;
    datosFila[9] = numeroDoc3Nom;
    datosFila[10] = montoDoc3Nom;
    datosFila[11] = numeroDoc4Nom;
    datosFila[12] = montoDoc4Nom;
    datosFila[13] = numeroDoc5Nom;
    datosFila[14] = montoDoc5Nom;
    datosFila[15] = numeroDoc6Nom;
    datosFila[16] = montoDoc6Nom;
    datosFila[17] = numeroDoc7Nom;
    datosFila[18] = montoDoc7Nom;
    datosFila[19] = numeroDoc8Nom;
    datosFila[20] = montoDoc8Nom;
    datosFila[21] = numeroDoc9Nom;
    datosFila[22] = montoDoc9Nom;
    datosFila[23] = numeroDoc10Nom;
    datosFila[24] = montoDoc10Nom;
    datosFila[25] = numeroDoc11Nom;
    datosFila[26] = montoDoc11Nom;
    datosFila[27] = montoDoc3Nom + montoDoc1Nom + montoDoc2Nom+ montoDoc4Nom 
                    + montoDoc5Nom + montoDoc6Nom+ montoDoc7Nom+ montoDoc8Nom
                    + montoDoc9Nom+ montoDoc10Nom+ montoDoc11Nom;
    datosFila[28] = emailProvNom;
    datosFila[29] = glosaNom;
    
    //llamo al objeto de la clase default y al metodo de addrow y le asigno el atributo datos fila.
    modeloTableNomina.addRow(datosFila);
    mostrarMensaje("Fila de pago agragada a la nomina con exito", "Info", "Agegado");
    
    
    txtRutNomina.setText(""); 
    txtNombreProvNomina.setText(""); 
    txtOpNomina.setText(""); 
    txtNumeroCuentaProvNom.setText(""); 
    txtCodigoCuentaProvNom.setText(""); 
    txtDoc1Nomina.setText(""); 
    txtMontoDoc1Nomina.setText(""); 
    txtDoc2Nomina.setText(""); 
    txtMontoDoc2Nomina.setText(""); 
    txtDoc3Nomina.setText(""); 
    txtMontoDoc3Nomina.setText(""); 
    txtDoc4Nomina.setText("");
    txtMontoDoc4Nomina.setText("");
    txtDoc5Nomina.setText("");
    txtMontoDoc5Nomina.setText("");
    txtDoc6Nomina.setText("");
    txtMontoDoc6Nomina.setText("");
    txtDoc7Nomina.setText("");
    txtMontoDoc7Nomina.setText("");
    txtDoc8Nomina.setText("");
    txtMontoDoc8Nomina.setText("");
    txtDoc9Nomina.setText("");
    txtMontoDoc9Nomina.setText("");
    txtDoc10Nomina.setText("");
    txtMontoDoc10Nomina.setText("");
    txtDoc11Nomina.setText("");
    txtMontoDoc11Nomina.setText("");
    
    txtEmailProvNomina.setText("");
    txtGlosaNomina.setText("");
     
    
    }//GEN-LAST:event_btnAgregarFilaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.sql.Connection cnx = null;
        try
            {
                cnx = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/portalPagosKovacs?serverTimezone=UTC", "root", "admin1234");}
        catch (java.sql.SQLException ex)
        {
        System.out.println("SQLException: " + ex.getMessage());System.out.println("SQLState: " + ex.getSQLState());
        System.out.println("VendorError: " + ex.getErrorCode());
        }
        
        try {
           
            ps = cnx.prepareStatement("Select * from proveedor where RUTPROV=?");
            ps.setString(1, txtRutNomina.getText());
            rs= ps.executeQuery();
            
            if(rs.next()) {
                txtNombreProvNomina.setText(String.valueOf(rs.getString("NOMBREPROV")));
                txtEmailProvNomina.setText(String.valueOf(rs.getString("EMAILPROV")));
                txtNumeroCuentaProvNom.setText(String.valueOf(rs.getInt("NUMEROCTAPROV")));
                txtCodigoCuentaProvNom.setText(String.valueOf(rs.getInt("CODIGOCTAPROV")));
                
            }else{
                JOptionPane.showMessageDialog(null, "No se encuentra el proveedor");
            }
        } catch (SQLException e) {
            System.out.println(" Erroe "+e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnExportarAExcellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarAExcellActionPerformed
        ExportarJtabletoExcell objNom;
        
        try {
            objNom = new ExportarJtabletoExcell();
            objNom.exportarExcel(tblDatosNomina);
        } catch (IOException ex) {
            System.out.println("Error: " + ex);
        }

        
    }//GEN-LAST:event_btnExportarAExcellActionPerformed

    private void tblDatosNominaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblDatosNominaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDatosNominaPropertyChange

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      cargarTabla();
    }//GEN-LAST:event_formWindowOpened

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarFila;
    private javax.swing.JButton btnExportarAExcell;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDatosNomina;
    private javax.swing.JTextField txtCodigoCuentaProvNom;
    private javax.swing.JTextField txtDoc10Nomina;
    private javax.swing.JTextField txtDoc11Nomina;
    private javax.swing.JTextField txtDoc1Nomina;
    private javax.swing.JTextField txtDoc2Nomina;
    private javax.swing.JTextField txtDoc3Nomina;
    private javax.swing.JTextField txtDoc4Nomina;
    private javax.swing.JTextField txtDoc5Nomina;
    private javax.swing.JTextField txtDoc6Nomina;
    private javax.swing.JTextField txtDoc7Nomina;
    private javax.swing.JTextField txtDoc8Nomina;
    private javax.swing.JTextField txtDoc9Nomina;
    private javax.swing.JTextField txtEmailProvNomina;
    private javax.swing.JTextField txtGlosaNomina;
    private javax.swing.JTextField txtMontoDoc10Nomina;
    private javax.swing.JTextField txtMontoDoc11Nomina;
    private javax.swing.JTextField txtMontoDoc1Nomina;
    private javax.swing.JTextField txtMontoDoc2Nomina;
    private javax.swing.JTextField txtMontoDoc3Nomina;
    private javax.swing.JTextField txtMontoDoc4Nomina;
    private javax.swing.JTextField txtMontoDoc5Nomina;
    private javax.swing.JTextField txtMontoDoc6Nomina;
    private javax.swing.JTextField txtMontoDoc7Nomina;
    private javax.swing.JTextField txtMontoDoc8Nomina;
    private javax.swing.JTextField txtMontoDoc9Nomina;
    private javax.swing.JTextField txtNombreProvNomina;
    private javax.swing.JTextField txtNumeroCuentaProvNom;
    private javax.swing.JTextField txtOpNomina;
    private javax.swing.JTextField txtRutNomina;
    // End of variables declaration//GEN-END:variables
    
    /**
     *
     */
    public void cargarTabla() {
       //Aqui se hace que la tabla no sea editable
      
       
       String titulosTabNomina[] = {"Rut Beneficiario", "Nombre Beneficiario", "Cod. Modalidad", 
            "Cta Abono", "Cod. Banco", "N Factura 1", "Monto 1", "N Factura 2", "Monto 2",
            "N Factura 3", "Monto 3", "N Factura 4", "Monto 4", "N Factura 5", "Monto 5",
            "N Factura 6", "Monto 6", "N Factura 7", "Monto 7", "N Factura 8", "Monto 8",
            "N Factura 9", "Monto 9", "N Factura 10", "Monto 10", "N Factura 11", "Monto 11",
            "Monto Total","Mail Beneficiario","Glosa"};
             
            modeloTableNomina.setColumnIdentifiers(titulosTabNomina);
            tblDatosNomina.setModel(modeloTableNomina);
            //Aca defino el tamaño de las columnas de la tabla
            tblDatosNomina.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblDatosNomina.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblDatosNomina.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblDatosNomina.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblDatosNomina.getColumnModel().getColumn(4).setPreferredWidth(80);
            tblDatosNomina.getColumnModel().getColumn(5).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(6).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(7).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(8).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(9).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(10).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(11).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(12).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(13).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(14).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(15).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(16).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(17).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(18).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(19).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(20).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(21).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(22).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(23).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(24).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(25).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(26).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(27).setPreferredWidth(90);
            tblDatosNomina.getColumnModel().getColumn(28).setPreferredWidth(200);
            tblDatosNomina.getColumnModel().getColumn(29).setPreferredWidth(250);

        
    }
    
    public void mostrarMensaje (String mensaje, String tipo, String titulo) {
        JOptionPane optionPane = new JOptionPane(mensaje);
        if (tipo.equals("info")) {
            optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        } 
        else if (tipo.equals("Error")) {
            optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
        }
        JDialog dialog = optionPane.createDialog(titulo);
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);        
    }
   
}
